apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-boot-demo-config
data:
  MONGODB_ENABLED: "false"

---
apiVersion: v1
kind: Secret
metadata:
  name: secret-sample
stringData:
  passwort: geheim